@ContactList.Server_HostAddress = http://localhost:5217

POST {{ContactList.Server_HostAddress}}/api/Users/logout/
Content-type: application/json
{
  "Username": "Jan Nowak",
  "Password": "SuperSilneHaslo123!"
}

